kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: clusteroperators.config.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.version
    description: The version the operator is at.
    name: Version
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].status
    description: Whether the operator is running and stable.
    name: Available
    type: string
  - JSONPath: .status.conditions[?(@.type=="Progressing")].status
    description: Whether the operator is processing changes.
    name: Progressing
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].lastTransitionTime
    description: The time the operator's Available status last changed.
    name: Since
    type: date
  group: config.openshift.io
  names:
    kind: ClusterOperator
    listKind: ClusterOperatorList
    plural: clusteroperators
    singular: clusteroperator
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
# XXX: This CRD will be removed before 4.0
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: clusteroperators.operatorstatus.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .status.version
    description: The version the operator is at.
    name: Version
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].status
    description: Whether the operator is running and stable.
    name: Available
    type: string
  - JSONPath: .status.conditions[?(@.type=="Progressing")].status
    description: Whether the operator is processing changes.
    name: Progressing
    type: string
  - JSONPath: .status.conditions[?(@.type=="Available")].lastTransitionTime
    description: The time the operator's Available status last changed.
    name: Since
    type: date
  group: operatorstatus.openshift.io
  names:
    kind: ClusterOperator
    listKind: ClusterOperatorList
    plural: clusteroperators
    singular: clusteroperator
  scope: Namespaced
  subresources:
    status: {}
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
---
# XXX: This CRD will be removed before 4.0
kind: CustomResourceDefinition
apiVersion: apiextensions.k8s.io/v1beta1
metadata:
  name: operatorstatuses.operatorstatus.openshift.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    description: CreationTimestamp is a timestamp representing the server time when
      this object was created.
    name: Age
    type: date
  group: operatorstatus.openshift.io
  names:
    kind: OperatorStatus
    listKind: OperatorStatusList
    plural: operatorstatuses
    singular: operatorstatus
  scope: Namespaced
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
