apiVersion: v1
kind: Service
metadata:
  name: cluster-version-operator
  namespace: openshift-cluster-version
  labels:
    k8s-app: cluster-version-operator
spec:
  type: ClusterIP
  selector:
    k8s-app: cluster-version-operator
  ports:
  - name: metrics
    port: 11345
